/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * AllowedFlexVolume represents a single Flexvolume that is allowed to be used.
 */
export class IoK8sApiPolicyV1beta1AllowedFlexVolume {
  /**
   * driver is the name of the Flexvolume driver.
   */
  "driver": string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<
    { name: string; baseName: string; type: string; format: string }
  > = [
    {
      "name": "driver",
      "baseName": "driver",
      "type": "string",
      "format": "",
    },
  ];

  static getAttributeTypeMap() {
    return IoK8sApiPolicyV1beta1AllowedFlexVolume.attributeTypeMap;
  }

  public constructor() {
  }
}
