/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * VolumeError captures an error encountered during a volume operation.
 */
export class IoK8sApiStorageV1alpha1VolumeError {
  /**
   * String detailing the error encountered during Attach or Detach operation. This string maybe logged, so it should not contain sensitive information.
   */
  "message"?: string;
  /**
   * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
   */
  "time"?: Date;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<
    { name: string; baseName: string; type: string; format: string }
  > = [
    {
      "name": "message",
      "baseName": "message",
      "type": "string",
      "format": "",
    },
    {
      "name": "time",
      "baseName": "time",
      "type": "Date",
      "format": "date-time",
    },
  ];

  static getAttributeTypeMap() {
    return IoK8sApiStorageV1alpha1VolumeError.attributeTypeMap;
  }

  public constructor() {
  }
}
