/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ExternalDocumentation allows referencing an external resource for extended documentation.
 */
export class IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation {
  "description"?: string;
  "url"?: string;

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<
    { name: string; baseName: string; type: string; format: string }
  > = [
    {
      "name": "description",
      "baseName": "description",
      "type": "string",
      "format": "",
    },
    {
      "name": "url",
      "baseName": "url",
      "type": "string",
      "format": "",
    },
  ];

  static getAttributeTypeMap() {
    return IoK8sApiextensionsApiserverPkgApisApiextensionsV1ExternalDocumentation
      .attributeTypeMap;
  }

  public constructor() {
  }
}
