/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

/**
* EndpointConditions represents the current condition of an endpoint.
*/
export class IoK8sApiDiscoveryV1beta1EndpointConditions {
    /**
    * ready indicates that this endpoint is prepared to receive traffic, according to whatever system is managing the endpoint. A nil value indicates an unknown state. In most cases consumers should interpret this unknown state as ready.
    */
    'ready'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ready",
            "baseName": "ready",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiDiscoveryV1beta1EndpointConditions.attributeTypeMap;
    }
    
    public constructor() {
    }
}

