/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1TypedLocalObjectReference } from './IoK8sApiCoreV1TypedLocalObjectReference.ts';
import { HttpFile } from '../http/http.ts';

/**
* IngressBackend describes all endpoints for a given service and port.
*/
export class IoK8sApiNetworkingV1beta1IngressBackend {
    'resource'?: IoK8sApiCoreV1TypedLocalObjectReference;
    /**
    * Specifies the name of the referenced service.
    */
    'serviceName'?: string;
    /**
    * IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.
    */
    'servicePort'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "resource",
            "baseName": "resource",
            "type": "IoK8sApiCoreV1TypedLocalObjectReference",
            "format": ""
        },
        {
            "name": "serviceName",
            "baseName": "serviceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "servicePort",
            "baseName": "servicePort",
            "type": "string",
            "format": "int-or-string"
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiNetworkingV1beta1IngressBackend.attributeTypeMap;
    }
    
    public constructor() {
    }
}

