/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from "../http/http.ts";

/**
* ServicePort contains information on service's port.
*/
export class IoK8sApiCoreV1ServicePort {
  /**
    * The application protocol for this port. This field follows standard Kubernetes label syntax. Un-prefixed names are reserved for IANA standard service names (as per RFC-6335 and http://www.iana.org/assignments/service-names). Non-standard protocols should use prefixed names such as mycompany.com/my-custom-protocol. This is a beta field that is guarded by the ServiceAppProtocol feature gate and enabled by default.
    */
  "appProtocol"?: string;
  /**
    * The name of this port within the service. This must be a DNS_LABEL. All ports within a ServiceSpec must have unique names. When considering the endpoints for a Service, this must match the 'name' field in the EndpointPort. Optional if only one ServicePort is defined on this service.
    */
  "name"?: string;
  /**
    * The port on each node on which this service is exposed when type=NodePort or LoadBalancer. Usually assigned by the system. If specified, it will be allocated to the service if unused or else creation of the service will fail. Default is to auto-allocate a port if the ServiceType of this Service requires one. More info: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
    */
  "nodePort"?: number;
  /**
    * The port that will be exposed by this service.
    */
  "port": number;
  /**
    * The IP protocol for this port. Supports \"TCP\", \"UDP\", and \"SCTP\". Default is TCP.
    */
  "protocol"?: string;
  /**
    * IntOrString is a type that can hold an int32 or a string.  When used in JSON or YAML marshalling and unmarshalling, it produces or consumes the inner type.  This allows you to have, for example, a JSON field that can accept a name or number.
    */
  "targetPort"?: (number | string);

  static readonly discriminator: string | undefined = undefined;

  static readonly attributeTypeMap: Array<
    { name: string; baseName: string; type: string; format: string }
  > = [
    {
      "name": "appProtocol",
      "baseName": "appProtocol",
      "type": "string",
      "format": "",
    },
    {
      "name": "name",
      "baseName": "name",
      "type": "string",
      "format": "",
    },
    {
      "name": "nodePort",
      "baseName": "nodePort",
      "type": "number",
      "format": "int32",
    },
    {
      "name": "port",
      "baseName": "port",
      "type": "number",
      "format": "int32",
    },
    {
      "name": "protocol",
      "baseName": "protocol",
      "type": "string",
      "format": "",
    },
    {
      "name": "targetPort",
      "baseName": "targetPort",
      "type": "string",
      "format": "int-or-string",
    },
  ];

  static getAttributeTypeMap() {
    return IoK8sApiCoreV1ServicePort.attributeTypeMap;
  }

  public constructor() {
  }
}
