/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiNodeV1alpha1Overhead } from './IoK8sApiNodeV1alpha1Overhead.ts';
import { IoK8sApiNodeV1alpha1Scheduling } from './IoK8sApiNodeV1alpha1Scheduling.ts';
import { HttpFile } from '../http/http.ts';

/**
* RuntimeClassSpec is a specification of a RuntimeClass. It contains parameters that are required to describe the RuntimeClass to the Container Runtime Interface (CRI) implementation, as well as any other components that need to understand how the pod will be run. The RuntimeClassSpec is immutable.
*/
export class IoK8sApiNodeV1alpha1RuntimeClassSpec {
    'overhead'?: IoK8sApiNodeV1alpha1Overhead;
    /**
    * RuntimeHandler specifies the underlying runtime and configuration that the CRI implementation will use to handle pods of this class. The possible values are specific to the node & CRI configuration.  It is assumed that all handlers are available on every node, and handlers of the same name are equivalent on every node. For example, a handler called \"runc\" might specify that the runc OCI runtime (using native Linux containers) will be used to run the containers in a pod. The RuntimeHandler must conform to the DNS Label (RFC 1123) requirements and is immutable.
    */
    'runtimeHandler': string;
    'scheduling'?: IoK8sApiNodeV1alpha1Scheduling;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "overhead",
            "baseName": "overhead",
            "type": "IoK8sApiNodeV1alpha1Overhead",
            "format": ""
        },
        {
            "name": "runtimeHandler",
            "baseName": "runtimeHandler",
            "type": "string",
            "format": ""
        },
        {
            "name": "scheduling",
            "baseName": "scheduling",
            "type": "IoK8sApiNodeV1alpha1Scheduling",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiNodeV1alpha1RuntimeClassSpec.attributeTypeMap;
    }
    
    public constructor() {
    }
}

