/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition } from './IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition.ts';
import { HttpFile } from '../http/http.ts';

export class IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus {
    /**
    * If request was approved, the controller will place the issued certificate here.
    */
    'certificate'?: string;
    /**
    * Conditions applied to the request, such as approval or denial.
    */
    'conditions'?: Array<IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "certificate",
            "baseName": "certificate",
            "type": "string",
            "format": "byte"
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<IoK8sApiCertificatesV1beta1CertificateSigningRequestCondition>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiCertificatesV1beta1CertificateSigningRequestStatus.attributeTypeMap;
    }
    
    public constructor() {
    }
}

