/**
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: unversioned
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { IoK8sApiCoreV1EnvFromSource } from './IoK8sApiCoreV1EnvFromSource.ts';
import { IoK8sApiCoreV1EnvVar } from './IoK8sApiCoreV1EnvVar.ts';
import { IoK8sApiCoreV1Volume } from './IoK8sApiCoreV1Volume.ts';
import { IoK8sApiCoreV1VolumeMount } from './IoK8sApiCoreV1VolumeMount.ts';
import { IoK8sApimachineryPkgApisMetaV1LabelSelector } from './IoK8sApimachineryPkgApisMetaV1LabelSelector.ts';
import { HttpFile } from '../http/http.ts';

/**
* PodPresetSpec is a description of a pod preset.
*/
export class IoK8sApiSettingsV1alpha1PodPresetSpec {
    /**
    * Env defines the collection of EnvVar to inject into containers.
    */
    'env'?: Array<IoK8sApiCoreV1EnvVar>;
    /**
    * EnvFrom defines the collection of EnvFromSource to inject into containers.
    */
    'envFrom'?: Array<IoK8sApiCoreV1EnvFromSource>;
    'selector'?: IoK8sApimachineryPkgApisMetaV1LabelSelector;
    /**
    * VolumeMounts defines the collection of VolumeMount to inject into containers.
    */
    'volumeMounts'?: Array<IoK8sApiCoreV1VolumeMount>;
    /**
    * Volumes defines the collection of Volume to inject into the pod.
    */
    'volumes'?: Array<IoK8sApiCoreV1Volume>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "env",
            "baseName": "env",
            "type": "Array<IoK8sApiCoreV1EnvVar>",
            "format": ""
        },
        {
            "name": "envFrom",
            "baseName": "envFrom",
            "type": "Array<IoK8sApiCoreV1EnvFromSource>",
            "format": ""
        },
        {
            "name": "selector",
            "baseName": "selector",
            "type": "IoK8sApimachineryPkgApisMetaV1LabelSelector",
            "format": ""
        },
        {
            "name": "volumeMounts",
            "baseName": "volumeMounts",
            "type": "Array<IoK8sApiCoreV1VolumeMount>",
            "format": ""
        },
        {
            "name": "volumes",
            "baseName": "volumes",
            "type": "Array<IoK8sApiCoreV1Volume>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IoK8sApiSettingsV1alpha1PodPresetSpec.attributeTypeMap;
    }
    
    public constructor() {
    }
}

